export const data = JSON.parse("{\"key\":\"v-71b4dc5e\",\"path\":\"/design_pattern/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F/%E9%97%A8%E9%9D%A2%E6%A8%A1%E5%BC%8F.html\",\"title\":\"门面模式\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"python\",\"date\":\"2024-01-03T00:00:00.000Z\",\"cover\":\"https://img.tucang.cc/api/image/show/6c8acb93bd0fc9dd85006746d572df8f\",\"category\":[\"python\"],\"tag\":[\"设计模式\",\"python\"],\"description\":\"门面模式 本章涉及内容： 结构型设计模式概要； 利用UML图理解门面设计模式； 提供了Python v3.5实现代码的真实用例； 门面模式与最少知识原则。 1. 什么是结构性设计模式\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://lianghexiang.github.io/space/space/design_pattern/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F/%E9%97%A8%E9%9D%A2%E6%A8%A1%E5%BC%8F.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"门面模式\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"门面模式 本章涉及内容： 结构型设计模式概要； 利用UML图理解门面设计模式； 提供了Python v3.5实现代码的真实用例； 门面模式与最少知识原则。 1. 什么是结构性设计模式\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://img.tucang.cc/api/image/show/6c8acb93bd0fc9dd85006746d572df8f\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"门面模式\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"L.H.X\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"设计模式\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"python\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-01-03T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"门面模式\\\",\\\"image\\\":[\\\"https://img.tucang.cc/api/image/show/6c8acb93bd0fc9dd85006746d572df8f\\\"],\\\"datePublished\\\":\\\"2024-01-03T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"L.H.X\\\",\\\"url\\\":\\\"/intro.html\\\"}]}\"]]},\"headers\":[{\"level\":3,\"title\":\"1. 什么是结构性设计模式\",\"slug\":\"_1-什么是结构性设计模式\",\"link\":\"#_1-什么是结构性设计模式\",\"children\":[]}],\"readingTime\":{\"minutes\":0.29,\"words\":88},\"filePathRelative\":\"design_pattern/设计模式/门面模式.md\",\"localizedDate\":\"2024年1月3日\",\"excerpt\":\"<h1> 门面模式</h1>\\n<p>本章涉及内容：</p>\\n<ol>\\n<li>\\n<p>结构型设计模式概要；</p>\\n</li>\\n<li>\\n<p>利用UML图理解门面设计模式；</p>\\n</li>\\n<li>\\n<p>提供了Python v3.5实现代码的真实用例；</p>\\n</li>\\n<li>\\n<p>门面模式与最少知识原则。</p>\\n</li>\\n</ol>\\n<h3> 1. 什么是结构性设计模式</h3>\\n\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
