export const themeData = JSON.parse("{\"encrypt\":{\"config\":{\"/demo/encrypt.html\":[\"$2a$10$yk4LKfljd4B7v0SbAKU9P.OXCyc5YGqnX0gu5PB3OKo3hIdLii0si\"]}},\"author\":{\"name\":\"L.H.X\",\"url\":\"/intro.html\"},\"logo\":\"/images/猫猫.svg\",\"repo\":\"vuepress-theme-hope/vuepress-theme-hope\",\"docsDir\":\"src\",\"footer\":\"\",\"displayFooter\":false,\"blog\":{\"timeline\":\"忽如白驹过隙\",\"description\":\"古道西风瘦马，夕阳西下；不积小流无以成江海，不积跬步无以至千里；\",\"intro\":\"/intro.html\",\"medias\":{\"Baidu\":\"https://baidu.com\",\"BiliBili\":\"https://bilibili.com\",\"Email\":\"lhx110396@163.com\",\"Gitee\":\"https://example.com\",\"GitHub\":\"https://example.com\",\"Gitlab\":\"https://example.com\",\"QQ\":\"https://example.com\",\"Qzone\":\"https://example.com\",\"Wechat\":\"https://example.com\",\"MrHope\":\"/intro.html\"}},\"locales\":{\"/\":{\"lang\":\"zh-CN\",\"navbarLocales\":{\"langName\":\"简体中文\",\"selectLangAriaLabel\":\"选择语言\"},\"metaLocales\":{\"author\":\"作者\",\"date\":\"写作日期\",\"origin\":\"原创\",\"views\":\"访问量\",\"category\":\"分类\",\"tag\":\"标签\",\"readingTime\":\"阅读时间\",\"words\":\"字数\",\"toc\":\"此页内容\",\"prev\":\"上一页\",\"next\":\"下一页\",\"lastUpdated\":\"上次编辑于\",\"contributors\":\"贡献者\",\"editLink\":\"在 GitHub 上编辑此页\",\"print\":\"打印\"},\"blogLocales\":{\"article\":\"文章\",\"articleList\":\"文章列表\",\"category\":\"分类\",\"tag\":\"标签\",\"timeline\":\"时间轴\",\"timelineTitle\":\"昨日不在\",\"all\":\"全部\",\"intro\":\"个人介绍\",\"star\":\"收藏\"},\"paginationLocales\":{\"prev\":\"上一页\",\"next\":\"下一页\",\"navigate\":\"跳转到\",\"action\":\"前往\",\"errorText\":\"请输入 1 到 $page 之前的页码！\"},\"outlookLocales\":{\"themeColor\":\"主题色\",\"darkmode\":\"外观\",\"fullscreen\":\"全屏\"},\"encryptLocales\":{\"iconLabel\":\"文章已加密\",\"placeholder\":\"输入密码\",\"remember\":\"记住密码\",\"errorHint\":\"请输入正确的密码\"},\"routeLocales\":{\"skipToContent\":\"跳至主要內容\",\"notFoundTitle\":\"页面不存在\",\"notFoundMsg\":[\"这里什么也没有\",\"我们是怎么来到这儿的？\",\"这 是 四 零 四 !\",\"看起来你访问了一个失效的链接\"],\"back\":\"返回上一页\",\"home\":\"带我回家\",\"openInNewWindow\":\"Open in new window\"},\"navbar\":[\"/\",{\"text\":\"博客\",\"icon\":\"book\",\"prefix\":\"/posts/\",\"children\":[{\"text\":\"Python\",\"icon\":\"python\",\"prefix\":\"python/\",\"children\":[{\"text\":\"BS4的使用\",\"icon\":\"spider\",\"link\":\"beautifulsoup\"},{\"text\":\"polygon面积计算\",\"icon\":\"fish\",\"link\":\"polygon面积计算\"},{\"text\":\"polygon边界简化\",\"icon\":\"cat\",\"link\":\"polygon边界简化\"}]}]},{\"text\":\"随笔\",\"icon\":\"pen\",\"prefix\":\"/anything/\",\"children\":[{\"text\":\"日记\",\"icon\":\"notebook\",\"prefix\":\"note/\",\"children\":[{\"text\":\"七七事变\",\"icon\":\"note\",\"link\":\"七七事变\"}]}]},{\"text\":\"时光轴\",\"icon\":\"clock\",\"link\":\"/timeline/\"}],\"sidebar\":{\"/\":[\"\",{\"text\":\"如何使用\",\"icon\":\"laptop-code\",\"prefix\":\"demo/\",\"link\":\"demo/\",\"children\":\"structure\"},{\"text\":\"博客\",\"icon\":\"book\",\"prefix\":\"posts/\",\"children\":\"structure\"},{\"text\":\"随笔\",\"icon\":\"pen\",\"prefix\":\"anything/\",\"children\":\"structure\"},\"intro\"]}}}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
