export const themeData = JSON.parse("{\"encrypt\":{},\"author\":{\"name\":\"L.H.X\",\"url\":\"/intro.html\"},\"darkmode\":\"switch\",\"repo\":\"lianghexiang/space\",\"docsDir\":\"src\",\"footer\":\"{{setupRunningTimeFooter}}\",\"displayFooter\":true,\"locales\":{\"/\":{\"lang\":\"zh-CN\",\"navbarLocales\":{\"langName\":\"简体中文\",\"selectLangAriaLabel\":\"选择语言\"},\"metaLocales\":{\"author\":\"作者\",\"date\":\"写作日期\",\"origin\":\"原创\",\"views\":\"访问量\",\"category\":\"分类\",\"tag\":\"标签\",\"readingTime\":\"阅读时间\",\"words\":\"字数\",\"toc\":\"此页内容\",\"prev\":\"上一页\",\"next\":\"下一页\",\"lastUpdated\":\"上次编辑于\",\"contributors\":\"贡献者\",\"editLink\":\"在GitHub上编辑此文章\",\"print\":\"打印\"},\"blogLocales\":{\"article\":\"文章\",\"articleList\":\"文章列表\",\"category\":\"分类\",\"tag\":\"标签\",\"timeline\":\"时间轴\",\"timelineTitle\":\"昨日不在\",\"all\":\"全部\",\"intro\":\"个人介绍\",\"star\":\"收藏\"},\"paginationLocales\":{\"prev\":\"上一页\",\"next\":\"下一页\",\"navigate\":\"跳转到\",\"action\":\"前往\",\"errorText\":\"请输入 1 到 $page 之前的页码！\"},\"outlookLocales\":{\"themeColor\":\"主题色\",\"darkmode\":\"外观\",\"fullscreen\":\"全屏\"},\"routeLocales\":{\"skipToContent\":\"跳至主要內容\",\"notFoundTitle\":\"页面不存在\",\"notFoundMsg\":[\"这里什么也没有\",\"我们是怎么来到这儿的？\",\"这 是 四 零 四 !\",\"看起来你访问了一个失效的链接\"],\"back\":\"返回上一页\",\"home\":\"带我回家\",\"openInNewWindow\":\"Open in new window\"},\"sidebar\":{\"/posts/\":\"structure\",\"/books/\":\"structure\",\"/人工智能/\":\"structure\",\"/diary/\":\"structure\"},\"navbar\":[{\"text\":\"博客\",\"icon\":\"fas fa-book-open\",\"prefix\":\"/posts/\",\"children\":[{\"text\":\"Python\",\"icon\":\"fa-brands fa-python\",\"link\":\"python/\"},{\"text\":\"常用工具\",\"link\":\"tools/\",\"icon\":\"fas fa-toolbox\"},{\"text\":\"设计模式\",\"icon\":\"fas fa-code\",\"link\":\"design_pattern/\"},{\"text\":\"gRPC\",\"icon\":\"fas fa-book\",\"link\":\"gRPC/\"}]},{\"text\":\"人工智能\",\"icon\":\"fab fa-android\",\"prefix\":\"/人工智能/\",\"children\":[{\"text\":\"大语言模型\",\"icon\":\"fab fa-android\",\"link\":\"LLM/\"}]},{\"text\":\"杂谈\",\"icon\":\"fab fa-diary\",\"prefix\":\"/diary/\",\"children\":[{\"text\":\"日记\",\"icon\":\"fab fa-android\",\"link\":\"小记/\"}]},{\"text\":\"时光轴\",\"icon\":\"fas fa-clock\",\"link\":\"/timeline/\"}],\"rtl\":false}},\"blog\":{\"timeline\":\"忽如白驹过隙\",\"description\":\"<font color='orange' size='3em'>行之有恒，久自芬芳；</font>\",\"intro\":\"/intro.html\",\"medias\":{\"Baidu\":\"https://baidu.com\",\"BiliBili\":\"https://space.bilibili.com/215138073\",\"Email\":\"lhx110396@163.com\",\"GitHub\":\"https://github.com/lianghexiang\",\"QQ\":\"https://example.com\",\"Qzone\":\"https://example.com\",\"Wechat\":\"https://example.com\"}},\"print\":false,\"fullscreen\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
